### PR TITLE
IAVLTree visualization

### PR DESCRIPTION
**Pull request by cloudhead**
Implement DOT graph output.

### CODE REVIEW

**Comment by adrianbrink** [comment]
@cloudhead Can you delete the branch or do you want to keep it around?

**Comment by cloudhead** [comment]
Interesting, I think it auto-closed when I deleted unstable.

**Comment by adrianbrink** [comment]
Yes, that happens on github. If you delete a branch, all PRs that are based on it will get closed.

**Comment by zramsay** [comment]
should this PR be re-opened in the IAVL repo?

**Comment by cloudhead** [comment]
It's already merged in iavl, let's close.

**Pull request closed without merging**
